/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Text,
  'bookId' : IDL.Text,
  'purchasedAt' : IDL.Int,
  'totalAmountCents' : IDL.Nat,
  'creatorPrincipal' : IDL.Principal,
  'buyerPrincipal' : IDL.Principal,
  'stripePaymentIntentId' : IDL.Text,
  'creatorShareCents' : IDL.Nat,
  'adminShareCents' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Book = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'offlineLocation' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Bool,
  'coverImageId' : ExternalBlob,
  'publishedAt' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'genre' : IDL.Text,
  'priceCents' : IDL.Nat,
});
export const ShortFilm = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'isPublished' : IDL.Bool,
  'thumbnailId' : ExternalBlob,
  'publishedAt' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'director' : IDL.Principal,
  'genre' : IDL.Text,
  'videoId' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPurchase' : IDL.Func([PurchaseRecord], [], []),
  'approveContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStripeCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text, StripeConfiguration],
      [IDL.Text],
      [],
    ),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteShortFilm' : IDL.Func([IDL.Text], [], []),
  'editBook' : IDL.Func([IDL.Text, Book], [], []),
  'editShortFilm' : IDL.Func([IDL.Text, ShortFilm], [], []),
  'fetchBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'fetchShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllPublishedContent' : IDL.Func(
      [],
      [
        IDL.Record({
          'shortFilms' : IDL.Vec(ShortFilm),
          'books' : IDL.Vec(Book),
        }),
      ],
      ['query'],
    ),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getAllShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreatorProfiles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'name' : IDL.Text,
            'role' : IDL.Text,
            'email' : IDL.Opt(IDL.Text),
            'phone' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getMyBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getMyEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getMyShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
  'getPublishedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getPublishedShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
  'getPurchasesByBuyer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'getPurchasesByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'getShortFilm' : IDL.Func([IDL.Text], [IDL.Opt(ShortFilm)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminBeenAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitBook' : IDL.Func([Book], [], []),
  'submitShortFilm' : IDL.Func([ShortFilm], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Text,
    'bookId' : IDL.Text,
    'purchasedAt' : IDL.Int,
    'totalAmountCents' : IDL.Nat,
    'creatorPrincipal' : IDL.Principal,
    'buyerPrincipal' : IDL.Principal,
    'stripePaymentIntentId' : IDL.Text,
    'creatorShareCents' : IDL.Nat,
    'adminShareCents' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Book = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'offlineLocation' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Bool,
    'coverImageId' : ExternalBlob,
    'publishedAt' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'genre' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  const ShortFilm = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'isPublished' : IDL.Bool,
    'thumbnailId' : ExternalBlob,
    'publishedAt' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'director' : IDL.Principal,
    'genre' : IDL.Text,
    'videoId' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPurchase' : IDL.Func([PurchaseRecord], [], []),
    'approveContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStripeCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text, StripeConfiguration],
        [IDL.Text],
        [],
      ),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteShortFilm' : IDL.Func([IDL.Text], [], []),
    'editBook' : IDL.Func([IDL.Text, Book], [], []),
    'editShortFilm' : IDL.Func([IDL.Text, ShortFilm], [], []),
    'fetchBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'fetchShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllPublishedContent' : IDL.Func(
        [],
        [
          IDL.Record({
            'shortFilms' : IDL.Vec(ShortFilm),
            'books' : IDL.Vec(Book),
          }),
        ],
        ['query'],
      ),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getAllShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatorProfiles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Text,
              'role' : IDL.Text,
              'email' : IDL.Opt(IDL.Text),
              'phone' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getMyBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getMyEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getMyShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
    'getPublishedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getPublishedShortFilms' : IDL.Func([], [IDL.Vec(ShortFilm)], ['query']),
    'getPurchasesByBuyer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getPurchasesByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getShortFilm' : IDL.Func([IDL.Text], [IDL.Opt(ShortFilm)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminBeenAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitBook' : IDL.Func([Book], [], []),
    'submitShortFilm' : IDL.Func([ShortFilm], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };