/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : string,
  'title' : string,
  'offlineLocation' : [] | [string],
  'isPublished' : boolean,
  'coverImageId' : ExternalBlob,
  'publishedAt' : [] | [bigint],
  'description' : string,
  'author' : Principal,
  'genre' : string,
  'priceCents' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface PurchaseRecord {
  'id' : string,
  'bookId' : string,
  'purchasedAt' : bigint,
  'totalAmountCents' : bigint,
  'creatorPrincipal' : Principal,
  'buyerPrincipal' : Principal,
  'stripePaymentIntentId' : string,
  'creatorShareCents' : bigint,
  'adminShareCents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface ShortFilm {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'isPublished' : boolean,
  'thumbnailId' : ExternalBlob,
  'publishedAt' : [] | [bigint],
  'description' : string,
  'director' : Principal,
  'genre' : string,
  'videoId' : ExternalBlob,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPurchase' : ActorMethod<[PurchaseRecord], undefined>,
  'approveContent' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createStripeCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string, StripeConfiguration],
    string
  >,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteShortFilm' : ActorMethod<[string], undefined>,
  'editBook' : ActorMethod<[string, Book], undefined>,
  'editShortFilm' : ActorMethod<[string, ShortFilm], undefined>,
  'fetchBooks' : ActorMethod<[], Array<Book>>,
  'fetchShortFilms' : ActorMethod<[], Array<ShortFilm>>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllPublishedContent' : ActorMethod<
    [],
    { 'shortFilms' : Array<ShortFilm>, 'books' : Array<Book> }
  >,
  'getAllPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getAllShortFilms' : ActorMethod<[], Array<ShortFilm>>,
  'getAllUserProfiles' : ActorMethod<
    [],
    Array<{ 'principal' : Principal, 'name' : string, 'role' : string }>
  >,
  'getBook' : ActorMethod<[string], [] | [Book]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatorProfiles' : ActorMethod<
    [],
    Array<
      {
        'principal' : Principal,
        'name' : string,
        'role' : string,
        'email' : [] | [string],
        'phone' : [] | [string],
      }
    >
  >,
  'getMyBooks' : ActorMethod<[], Array<Book>>,
  'getMyEarnings' : ActorMethod<[], bigint>,
  'getMyPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getMyShortFilms' : ActorMethod<[], Array<ShortFilm>>,
  'getPublishedBooks' : ActorMethod<[], Array<Book>>,
  'getPublishedShortFilms' : ActorMethod<[], Array<ShortFilm>>,
  'getPurchasesByBuyer' : ActorMethod<[Principal], Array<PurchaseRecord>>,
  'getPurchasesByCreator' : ActorMethod<[Principal], Array<PurchaseRecord>>,
  'getShortFilm' : ActorMethod<[string], [] | [ShortFilm]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminBeenAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'rejectContent' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitBook' : ActorMethod<[Book], undefined>,
  'submitShortFilm' : ActorMethod<[ShortFilm], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];